replicaCount: 1
image:
  repository: andynze4/flask-app
  pullPolicy: IfNotPresent
  tag: 3fd2d4
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5001
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
<<<<<<< HEAD
    - host: flask.local
      paths:
        - path: /
          pathType: Prefix
=======
  - host: flask-app.test.com
    paths:
    - path: /
      pathType: Prefix
>>>>>>> e94d897 (Update-ArgoCD)
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 50M
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
