name: Test and Build

on:
  push:
    branches:
      - master
    # paths:
    #   - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          
      # Test the Code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .

      - name: Docker Credentials
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t andynze4/demo-app:${{ env.VERSION }} 
      
      - name: Test Docker Login
        run: |
          docker info
          
      # Push the Docker Image
      - name: Push Docker Image
        run: |
          docker push andynze4/demo-app:${{ env.VERSION }}
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3 # Cloneing the Repo
      
      # UPdate the K8s Manifest Files
      - name: Update K8s Manifests
        run: |
          cat deploy/deploy.yaml
          sed -i "s|image: andynze4/demo-app:.*|image: andynze4/demo-app:${{ env.VERSION }}|g" deploy/deploy.yaml
          cat deploy/deploy.yaml

      # Update Github
      - name: Commit the changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add deploy/deploy.yaml
          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/infosecsingh/Flask-App-GitHub-Actions-ArgoCD.git
          git push origin master

   # Download and install ArgoCD CLI from Installation.
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --username ${{ secrets.ARGOCD_USER }} \
          --password ${{ secrets.ARGOCD_PASSWORD }} \
          --insecure \
          --grpc-web

          argocd app sync python-app
     


        
      

